language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install: pip install -r requirements.txt
script:
  - py.test --cov=firebasedata --cov-branch
  - flake8
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: 'sdist bdist_wheel'
  user:
    secure: M5Xq89G8JgBoGFp3aMIJUMUhXOJJ/idyePk2GXzJE916YsbCNoi0Qv8MNV6BA9pSY+UjQo8+4Gm2Ilu52uATehnpSmz6zZnB6Ce48k+Er3LHWApzQ0PD0umul69ogCOuFjmLll+wfwqy846G5qL1h7dfraTE9hOOpHGwEHatIafxDTSQtG8EZCalpKSMfTKBK1eNW9bdofEfCg9TEUxXeqC9EEkD+wkMvrVey2rHU5kXTs4u6HKUYvTMyyv8B1OCoNuh4PjNoUk6RgB4nCvDDPyIi98IL94fQmm/fD9oQXN89Yyaw96wlNVSD3SOo8XgrmgVuiezAnbpcn+3cjJdk38OJ6WEV57MIYOWGw8MsxdS689MEGd8AOd7iN9qmo0br2DTOi01GJAEkn/vPviatkkdmNa/1lNlAu1Xgn3gOjo6j0NaKHWnf1M3CsU8C/59fwNKfXevjsPg/zyfgnFgLqGKyqFjBZgi6sP/C06Boex5r8eLKJxFYlyXS2Jw70L4Klc51nHZeoto4JyYTdqWtWfmBbLwrgJyyScsFdDbmmCDnMmpM88ione+D7pmJoyvMiqRnfMQtBJh/Tvh2caggFi2v/W6wBpvQHJ6EbHxc6vqfNN+omMGfoewVKV6pLjkMpWPmtKrUH19wvTEegrZILvZ57EGAwqiD77izZ86qXE=
  password:
    secure: PLE1pZUOm7mVhD8ijWQDDT23gdrQ7RRxaGMEkqbY5jYtkHZcy6HmarrRKnedAEFYkq9NJYANZ3BTpt4hQCjEvy1cwuAdAeVLxwKfSxBzgb6gI3QQKmxsk934AwRnT5g7t9ZxVu79E5Uf5QQ9/Lt0rKRTjnQJty/QHOwarFablbTGcQXFz00aTlNqagegvgS3nxs1GNkYJcWjDrpnPdMfK2G3p+0R7nKWQP7WK9hMp97+DdVycLVHzA6svbE0kswrdjkc/b0k04drXMVoel+SPHT68lAEB3iInRPbb/Q4Wp9Z1VRFH5COY3ESghBmQftzzK9Lwt8/fKBNF4zphpzE5KWFMp5c9Fi4ZI5PQPOGRBK1++wRwHFq+/f2TNmG4oJCFBnZbPlfACv+UVrHcyev02ge40IRHVubecB6jCzUrOYB/BAHbJeORPlrB4pQggLkQduPeGNa72O9BcJkjj8M0PD+RQaqU1CpZGgDbquaX2/MudHsrgAaMaREP75WT1WckS4k+0oX1shWr7p62mbDfGe/y6lV7zLrocEq8PocIjpa82e/gTFxY2mZn1FBXeguFiCV9D335nsS7OS2jgz/vCsp9vMQMfMcOoPDjrY9S+DlCl6G7v3KexkyfbvEmYuV//iNSDNDVV4ASl9SQ/MtFooWiPcuw3OEGK9j+96Uovo=
  on:
    tags: true
    python: '3.9'
